Repository Sylius/CmsPlugin, pull requests merged in 2025-10, with the labels that each got.

#108 Update Sylius documentation link in README
  README.md
Labels: Documentation, Maintenance

#111 Create form type for content element only if it doesn't exist
  src/DependencyInjection/Compiler/ContentElementPass.php
Labels: Bug

#112 [CI] Remove builds for unsupported Symfony 7.2
  .github/workflows/build.yaml
Labels: CI, Maintenance
